// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFgrYoG5L4bhC7BsxL9ZfVu6ZPIffJO68',
    appId: '1:1066731165724:web:e9aee17b48493c653f67d9',
    messagingSenderId: '1066731165724',
    projectId: 'nigel-flutterbasic-89914',
    authDomain: 'nigel-flutterbasic-89914.firebaseapp.com',
    databaseURL: 'https://nigel-flutterbasic-89914-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nigel-flutterbasic-89914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSA7PnSApb1rZ6KE-xz6tlKXuwCoFj-so',
    appId: '1:1066731165724:android:f4b092133ae7db083f67d9',
    messagingSenderId: '1066731165724',
    projectId: 'nigel-flutterbasic-89914',
    databaseURL: 'https://nigel-flutterbasic-89914-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nigel-flutterbasic-89914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjin_vaL9F1gdR-bSfg3vvFEErPEE1ASk',
    appId: '1:1066731165724:ios:c6770909f0cf71ce3f67d9',
    messagingSenderId: '1066731165724',
    projectId: 'nigel-flutterbasic-89914',
    databaseURL: 'https://nigel-flutterbasic-89914-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nigel-flutterbasic-89914.appspot.com',
    iosClientId: '1066731165724-qbmvv4r7q8rgr7q964ohcjclk7rrbggo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nigelFlutterbasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjin_vaL9F1gdR-bSfg3vvFEErPEE1ASk',
    appId: '1:1066731165724:ios:c6770909f0cf71ce3f67d9',
    messagingSenderId: '1066731165724',
    projectId: 'nigel-flutterbasic-89914',
    databaseURL: 'https://nigel-flutterbasic-89914-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nigel-flutterbasic-89914.appspot.com',
    iosClientId: '1066731165724-qbmvv4r7q8rgr7q964ohcjclk7rrbggo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nigelFlutterbasic',
  );
}
